language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1
  
before_install:
  - sudo apt-get update -q
  - sudo apt-get autoremove graphviz -y
  - sudo apt-get install graphviz -y

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
